### ISSUE TITLE
IllegalArgumentException: Unable to load native library

### ISSUE THREAD

**Issue by arekmd** [cnlohr/rawdrawandroid#19]
Hi, 
I'm trying to run this code on my old Asus phone (Android 6.0.1). App window immediately closes, logcat shows this:

```
07-17 18:13:46.638 10951 10951 D AndroidRuntime: Shutting down VM
07-17 18:13:46.638 10951 10951 E AndroidRuntime: FATAL EXCEPTION: main
07-17 18:13:46.638 10951 10951 E AndroidRuntime: Process: org.yourorg.cnfgtest, PID: 10951
07-17 18:13:46.638 10951 10951 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.yourorg.cn
fgtest/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/org.yourorg.cnfgt
est-1/lib/arm/libcnfgtest.so
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:24
35)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:249
5)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.ActivityThread.access$900(ActivityThread.java:154)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:153)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5472)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.j
ava:726)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-17 18:13:46.638 10951 10951 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to load native library: /da
ta/app/org.yourorg.cnfgtest-1/lib/arm/libcnfgtest.so
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.NativeActivity.onCreate(NativeActivity.java:182)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6323)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1
108)
07-17 18:13:46.638 10951 10951 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:23
88)

```

My setup:
```
export ANDROID_HOME=~/android/android-sdk-linux
export NDK=~/android/android-ndk-r21d
```

**Comment by dreua** [comment]
Can you check if this file exists on your phone `/data/app/org.yourorg.cnfgt
est-1/lib/arm/libcnfgtest.so` via Android Studio's DeviceFile Explorer or `adb shell`? It probably doesn't, maybe the build logs can shed some light on why that is.

**Comment by arekmd** [comment]
Unfortunately my phone is not rooted. I cannot access to  /data/app directory. 

I installed the same package on my other phone running Android 8.0.0, and demo app run perfectly. Weird.

**Comment by dreua** [comment]
> Unfortunately my phone is not rooted. I cannot access to /data/app directory.

Neither is mine, but I still can access the data directories, at least of the apps I built and installed from source. Maybe this is different in Android versions, but be aware that you might still be able to got to your target even if `ls` gives you a `Permission denied` for `/data` and `/data/app`.

> I installed the same package on my other phone running Android 8.0.0, and demo app run perfectly. Weird.

That could be explained by different ABIs (processor architectures), there are [4 currently supported and 3 more deprecated](https://developer.android.com/ndk/guides/abis#sa) so it's quite possible your two phones don't have the same. Given your phone models it should be possible to research what ABIs you need and maybe find the reason it fails for the Asus.

Please post the output of your make command. Probably best to do a `make clean` first to be sure we see the whole build.

**Comment by dreua** [comment]
For x86 and x86_64 you'd need to edit these lines: https://github.com/cnlohr/rawdrawandroid/blob/master/Makefile#L93-L97

**Comment by arekmd** [comment]
Build log:

```
mkdir -p makecapk/lib/arm64-v8a
/home/arek/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang -ffunction-sections -Os -fdata-sections -Wall -fvisibility=hidden -Os -DANDROID -DAPPNAME=\"cnfgtest\" -I./rawdraw -I/home/arek/android/android-ndk-r21d/sysroot/u
sr/include -I/home/arek/android/android-ndk-r21d/sysroot/usr/include/android -fPIC -I. -DANDROIDVERSION=29 -m64 -o makecapk/lib/arm64-v8a/libcnfgtest.so test.c android_native_app_glue.c -L/home/arek/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/
usr/lib/aarch64-linux-android/29 -Wl,--gc-sections -s -lm -lGLESv3 -lEGL -landroid -llog -shared -uANativeActivity_onCreate
test.c:32:7: warning: 'ASensorManager_getInstance' is deprecated [-Wdeprecated-declarations]
        sm = ASensorManager_getInstance();
             ^
/home/arek/android/android-ndk-r21d/sysroot/usr/include/android/sensor.h:557:17: note: 'ASensorManager_getInstance' has been explicitly marked deprecated here
__attribute__ ((deprecated)) ASensorManager* ASensorManager_getInstance();
                ^
1 warning generated.
mkdir -p makecapk/lib/armeabi-v7a
/home/arek/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi29-clang -ffunction-sections -Os -fdata-sections -Wall -fvisibility=hidden -Os -DANDROID -DAPPNAME=\"cnfgtest\" -I./rawdraw -I/home/arek/android/android-ndk-r21d/sysroo
t/usr/include -I/home/arek/android/android-ndk-r21d/sysroot/usr/include/android -fPIC -I. -DANDROIDVERSION=29 -mfloat-abi=softfp -m32 -o makecapk/lib/armeabi-v7a/libcnfgtest.so test.c android_native_app_glue.c -L/home/arek/android/android-ndk-r21d/toolchains/llvm/prebui
lt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/29 -Wl,--gc-sections -s -lm -lGLESv3 -lEGL -landroid -llog -shared -uANativeActivity_onCreate
test.c:32:7: warning: 'ASensorManager_getInstance' is deprecated [-Wdeprecated-declarations]
        sm = ASensorManager_getInstance();
             ^
/home/arek/android/android-ndk-r21d/sysroot/usr/include/android/sensor.h:557:17: note: 'ASensorManager_getInstance' has been explicitly marked deprecated here
__attribute__ ((deprecated)) ASensorManager* ASensorManager_getInstance();
                ^
1 warning generated.
mkdir -p makecapk/assets
echo "Test asset file" > makecapk/assets/asset.txt
rm -rf temp.apk
/home/arek/android/android-sdk-linux/build-tools/24.0.0/aapt package -f -F temp.apk -I /home/arek/android/android-sdk-linux/platforms/android-29/android.jar -M AndroidManifest.xml -S Sources/res -A makecapk/assets -v --target-sdk-version 29
Found 1 custom asset file in makecapk/assets
Configurations:
 (default)

Files:
  assets/asset.txt
    Src: () makecapk/assets/asset.txt
  mipmap/icon.png
    Src: () Sources/res/mipmap/icon.png
  values/strings.xml
    Src: () Sources/res/values/strings.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type mipmap
    mipmap/icon.png
      Src: () Sources/res/mipmap/icon.png
  Type values
    values/strings.xml
      Src: () Sources/res/values/strings.xml
Including resources from package: /home/arek/android/android-sdk-linux/platforms/android-29/android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: Sources/res/mipmap/icon.png
    (processed image Sources/res/mipmap/icon.png: 100% size of source)
    (new resource id icon from mipmap/icon.png #generated)
Creating 'temp.apk'
Writing all files...
      'AndroidManifest.xml' (compressed 63%)
      'assets/asset.txt' (not compressed)
      'res/mipmap/icon.png' (not compressed)
      'resources.arsc' (not compressed)
Generated 4 files
Included 0 files from jar/zip files.
Checking for deleted files
Done!
unzip -o temp.apk -d makecapk
Archive:  temp.apk
  inflating: makecapk/AndroidManifest.xml
 extracting: makecapk/assets/asset.txt
 extracting: makecapk/res/mipmap/icon.png
 extracting: makecapk/resources.arsc
rm -rf makecapk.apk
cd makecapk && zip -D9r ../makecapk.apk .
  adding: res/mipmap/icon.png (deflated 8%)
  adding: resources.arsc (deflated 72%)
  adding: assets/asset.txt (stored 0%)
  adding: AndroidManifest.xml (deflated 63%)
  adding: lib/armeabi-v7a/libcnfgtest.so (deflated 53%)
  adding: lib/arm64-v8a/libcnfgtest.so (deflated 59%)
jarsigner -sigalg SHA1withRSA -digestalg SHA1 -verbose -keystore my-release-key.keystore -storepass password makecapk.apk standkey
   adding: META-INF/MANIFEST.MF
   adding: META-INF/STANDKEY.SF
   adding: META-INF/STANDKEY.RSA
  signing: res/mipmap/icon.png
  signing: resources.arsc
  signing: assets/asset.txt
  signing: AndroidManifest.xml
  signing: lib/armeabi-v7a/libcnfgtest.so
  signing: lib/arm64-v8a/libcnfgtest.so
>>> Signer
    X.509, CN=example.com, OU=ID, O=Example, L=Doe, ST=John, C=GB
    [trusted certificate]

jar signed.

Warning:
The signer's certificate is self-signed.
rm -rf cnfgtest.apk
/home/arek/android/android-sdk-linux/build-tools/24.0.0/zipalign -v 4 makecapk.apk cnfgtest.apk
Verifying alignment of cnfgtest.apk (4)...
      50 META-INF/MANIFEST.MF (OK - compressed)
     446 META-INF/STANDKEY.SF (OK - compressed)
     910 META-INF/STANDKEY.RSA (OK - compressed)
    2082 res/mipmap/icon.png (OK - compressed)
    2239 resources.arsc (OK - compressed)
    2596 assets/asset.txt (OK)
    2685 AndroidManifest.xml (OK - compressed)
    3600 lib/armeabi-v7a/libcnfgtest.so (OK - compressed)
   19869 lib/arm64-v8a/libcnfgtest.so (OK - compressed)
Verification succesful
rm -rf temp.apk
rm -rf makecapk.apk
-rw-rw-r-- 1 arek arek 36445 lip 14 21:01 cnfgtest.apk
```

**Comment by dreua** [comment]
The build log looks good to me, not sure if I can remote-debug this any further. You may not have the latest version of rawdrawandroid and and Android sdk/ndk tools, so you might want to try updating that. I don't have high hopes here though.

**Comment by dreua** [comment]
Feel free to reopen, sorry I couldn't help any more here.

**Comment by trholding** [comment]
Re-opening but I do not expect a solution, so can be closed. Just leaving it here for folks who may need to support older versions of android and are brave enough to write a fix for this in rawdrawandroid...

I ran a test app on a Jailbroken Kindle Paperwhite with Android 5.1.1 API Level 22.

The app started and crashed with this error:

```
I/ActivityManager(  429): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.test.rdat/android.app.NativeActivity} from uid 10043 on display 0
V/WindowManager(  429): addAppToken: AppWindowToken{2cc30d96 token=Token{384ab4b1 ActivityRecord{27b86b58 u0 org.test.rdat/android.app.NativeActivity t201}}} to stack=1 task=201 at 0
V/WindowManager(  429): Adding window Window{3f96396e u0 Starting org.test.rdat} at 4 of 9 (after Window{150b835b u0 com.android.settings/com.android.settings.Settings})
I/ActivityManager(  429): Start proc 2268:org.test.rdat/u0a49 for activity org.test.rdat/android.app.NativeActivity
W/linker  ( 2268): librdat.so: unused DT entry: type 0x6ffffef5 arg 0x96c
W/linker  ( 2268): librdat.so: unused DT entry: type 0x6ffffffe arg 0x94c
W/linker  ( 2268): librdat.so: unused DT entry: type 0x6fffffff arg 0x1
E/AndroidRuntime( 2268): Process: org.test.rdat, PID: 2268
E/AndroidRuntime( 2268): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.test.rdat/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/org.test.rdat-1/lib/arm/librdat.so
E/AndroidRuntime( 2268): Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/org.test.rdat-1/lib/arm/librdat.so
W/ActivityManager(  429):   Force finishing activity 1 org.test.rdat/android.app.NativeActivity
I/WindowManager(  429): Screenshot max retries 4 of Token{384ab4b1 ActivityRecord{27b86b58 u0 org.test.rdat/android.app.NativeActivity t201 f}} appWin=Window{3f96396e u0 Starting org.test.rdat} drawState=4
W/ActivityManager(  429): Activity pause timeout for ActivityRecord{27b86b58 u0 org.test.rdat/android.app.NativeActivity t201 f}
W/PackageManager(  533): Failure retrieving resources for org.test.rdat: Resource ID #0x0
I/ActivityManager(  429): Process org.test.rdat (pid 2268) has died
```

I checked the presence of the lib:

```
root@heisenberg:/data # ls /data/app/org.test.rdat-1/lib/arm/
librdat.so
```

The solution to probably getting to run this on older versions maybe:

 https://stackoverflow.com/a/22729423

```
package <YourActivityName>;

public class YourActivityName extends android.app.NativeActivity {

    static {
       System.loadLibrary("YourLibName");
    }
 }
```
Then include YourActivityName instead of android.app.NativeActivity in AndroidManfest.xml

Then apply this:
https://github.com/cnlohr/rawdrawandroid/issues/68#issue-1923335109

Since Java is not my cup of tea, I leave this for someone brave to explore. Good Luck! And please share findings.

**Comment by cnlohr** [comment]
Did you make sure to compile targeting 32-bit instead of 64-bit?  By default, rawdrawandroid now targets 64-bit.

**Comment by trholding** [comment]
> Did you make sure to compile targeting 32-bit instead of 64-bit?  By default, rawdrawandroid now targets 64-bit.
> 
> See this line here: https://github.com/cnlohr/rawdrawandroid/blob/master/Makefile#L103

Yes this was uncommented:
TARGETS += makecapk/lib/armeabi-v7a/lib$(APPNAME).so
