### ISSUE TITLE
Error when installing SDK and NDK

### ISSUE THREAD

**Issue by kiromaisus** [cnlohr/rawdrawandroid#35]
I tried to run the **rawdrawandroidexample**.

I tried "make" and then

```
ruvian@DESKTOP-M440L4C:~/rawdrawandroidexample$ make
mkdir -p makecapk/assets
echo "Test asset file" > makecapk/assets/asset.txt
rm -rf temp.apk
/home/ruvian/android-sdk/build-tools/29.0.3/aapt package -f -F temp.apk -I /home/ruvian/android-sdk/platforms/android-22/android.jar -M AndroidManifest.xml -S Sources/res -A makecapk/assets -v --target-sdk-version 28
Found 1 custom asset file in makecapk/assets
Configurations:
 (default)

Files:
  assets/asset.txt
    Src: () makecapk/assets/asset.txt
  mipmap/icon.png
    Src: () Sources/res/mipmap/icon.png
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type mipmap
    mipmap/icon.png
      Src: () Sources/res/mipmap/icon.png
Including resources from package: /home/ruvian/android-sdk/platforms/android-22/android.jar
W/asset   ( 4726): Asset path /home/ruvian/android-sdk/platforms/android-22/android.jar is neither a directory nor file (type=1).
ERROR: Asset package include '/home/ruvian/android-sdk/platforms/android-22/android.jar' not found.
make: *** [rawdrawandroid/Makefile:128: makecapk.apk] Error 1`
```

Then thought, ok, maybe if I try to reinstall from the beginning, so I did
```
ruvian@DESKTOP-M440L4C:~/rawdrawandroidexample$ $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;29.0.3" "cmake;3.10.2.4988404" "ndk;21.1.6352462" "patcher;v4" "platform-tools" "platforms;android-24" "tools"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```
But errors again. I'm not that knowledged in these things, a friend of mine tried to help me, we got far, but I just don't know what to do now.

**Comment by kiromaisus** [comment]
So, I've been trying lots of things and I suggest to retry everything of the readme.md, because I don't remember for sure which of the errors I got was my fault and which wasn't.
The solution to this was to change the ANDROIDVERSION and ANDROIDTARGET in the Makefile (inside the project) to match to the version of the directory ~/android-sdk/platform/android-**24**
So they became
`ANDROIDVERSION=24
ANDROIDTARGET=24`

Also the
`make clean all push run`
was crucial to make things work in the final.

**Comment by dreua** [comment]
@kiromaisus I'm sorry that you didn't get a response for such a long time. Is this still an issue? Did you find a solution? I installed NDK and that stuff via Android studio, maybe you could do that as a workaround.

**Comment by kiromaisus** [comment]
@dreua The second post I did was the solution me and my friend found out and worked.

**Comment by dreua** [comment]
Alright, thank you! I'll close this issue then.

**Comment by dreua** [comment]
Btw I think a different solution would be to install the SDK version that is used in the Makefile.
